#!/bin/bash

# Default Homebrew Path
HBREW_PATH=$HOME/.local

# Default Google-drive Path
GOOGLE_DRIVE=$HOME/.google-drive

# Default texlive base path
texlive_base_path=$HOME/.texlive

# Basic aliases
alias ls='ls -p -F -h --color=auto --show-control-chars'
alias ll='ls -la'
alias l='ls -p -F -h --color=auto --show-control-chars'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias grep='grep --color'
alias df='df -h'
alias rsync='rsync -azvh --info=progress2'
alias sudo='sudo -H'

# Delete certain files recursively!!
delete_recursive ()
{
  echo "Querying files!!"
  echo "================================"
  if [ -x "$(command -v fd)" ]; then
    fd -IH -g "$1" -tf
  else
    find . -name "$1" -type f
  fi
  echo "================================"
  read -p "Do you wish to delete them? [yn]" yn
  while true; do
    case $yn in
      [Yy]* )
        if [ -x "$(command -v fd)" ]; then
          if [ -x "$(command -v rip)"]; then
            fd -IH -g "$1" -tf -X rip
          else
            fd -IH -g "$1" -tf -X rm
          fi
        else
          find . -name "$1" -type f -delete
        fi
        echo "Deleted the files!!"
        ;;
	  [Nn]* )
	    echo "Not deleting!!"; break
	    ;;
	  * )
	    echo "Please answer y or n."
	    ;;
    esac
  done
}

# VNC stuff
if [ -x "$(command -v vncserver)" ]; then
	echo "** VNC server found! **"
	echo " To start: vncstart"
	echo " To end: vnckill"
	echo ""
	alias vncstart="vncserver -localhost no -useold -geometry 1200x800 -depth 32"
	alias vnckill="vncserver -kill :1"
fi

# Get Linux distro. info.
ARCH=$(uname -m)
KERNEL=$(uname -r)
if [ -n "$(command -v lsb_release)" ]; then
    DISTRONAME=$(lsb_release -s -d)
elif [ -f "/etc/os-release" ]; then
    DISTRONAME=$(grep PRETTY_NAME /etc/os-release | sed 's/PRETTY_NAME=//g' | tr -d '="')
elif [ -f "/etc/debian_version" ]; then
    DISTRONAME="Debian $(cat /etc/debian_version)"
elif [ -f "/etc/redhat-release" ]; then
    DISTRONAME=$(cat /etc/redhat-release)
else
    DISTRONAME="$(uname -s) $(uname -r)"
fi

# The homebrew path!!
if [ -d $HBREW_PATH ]; then
  export HOMEBREW=$HBREW_PATH
  echo "HOMEBREW directory is $HOMEBREW"
  export PATH=$HOMEBREW/bin:$HOMEBREW/opt/bin:/opt/bin/:$PATH
fi

# Setting for JRE
JAVA_HOME=/opt/java
if [ -d $JAVA_HOME ]; then
    echo "Java (Possibly Oracle) found at $JAVAHOME"
    export PATH=$JAVA_HOME/bin:$PATH
	export CLASSPATH=$JAVA_HOME/lib
fi
# Javafx
JAVAFX_HOME=/opt/javafx
if [ -d $JAVAFX_HOME ]; then
	echo "JavaFX found!"
	export JAVAFX_HOME=/opt/javafx/lib
fi


# Rust
if [ -d $HOME/.cargo ]; then
	echo "Cargo directory detected at $HOME/.cargo"
	# export PATH=$HOME/.cargo/bin:$PATH
	source $HOME/.cargo/env
fi

# Exa
if [ -x "$(command -v exa)" ]; then
	echo "exa found! using it instead of ls"
	alias ls='exa -hF'
	alias ll='exa -lahF'
	alias l='exa -hF'
fi

# Lsd
if [ -x "$(command -v lsd)" ]; then
	echo "lsd found! using it instead of ls or exa"
	alias ls='lsd -hFX'
	alias ll='lsd -lahFX'
	alias l='lsd -hFX'
fi

# Bat
if [ -x "$(command -v bat)" ]; then
	echo "Bat found! using it instead of cat"
	alias cat='bat'
fi

# Neovim
if [ -x "$(command -v nvim)" ]; then
	echo "Neovim found! replacing vim!"
	alias vim="nvim"
	alias vi="nvim"
fi

# Texlive
texlive_year="2020"
texlive_arch=x86_64-linux
texlive_bin_dir=$texlive_base_path/$texlive_year/bin/$texlive_arch/
texlive_bin_dir_woyear=$texlive_base_path/bin/$texlive_arch/
if [ -d $texlive_bin_dir ]; then
    echo "Texlive found at $texlive_bin_dir directory!! Adding to path!"
    export PATH=$texlive_bin_dir:$PATH
elif [ -d $texlive_bin_dir_woyear ]; then
	echo "Texlive found at $texlive_bin_dir_woyear directory!! Adding to path!"
	export PATH=$texlive_bin_dir_woyear:$PATH
fi

# Rip
trash_location="$HOME/.local/share/Trash/files/"
if [ -x "$(command -v rip)" ]; then
	echo "rip, rm-improved found! Setting up graveyard at $trash_location"
	alias rip="rip --graveyard $trash_location"
fi

# bpytop
if [ -x "$(command -v $HOMEBREW/bin/pip3)" ]; then
  if [ -x "$(command -v $HOMEBREW/bin/bpytop)" ]; then
    echo "Locally installed bpytop found!"
	alias bpytop="$HOMEBREW/bin/pip3 install -U bpytop && bpytop"
  fi
fi

# pypy
if [ -x "$(command -v $HOMEBREW/opt/pypy/bin/pypy3)" ]; then
  echo "pypy3 found in $HOMEBREW/opt/pypy/bin/pypy3 !! Extending PATH!"
  export PATH=$HOMEBREW/opt/pypy/bin:$PATH
fi

# IrfanView
iview64_path=$HOME/.wine/drive_c/Program\ Files/IrfanView/i_view64.exe
run_iview ()
{
  wine "$iview64_path" `winepath --windows $@`
}
if [ -x "$(command -v wine)" ]; then
  if [ -f "$iview64_path" ]; then
    echo "Irfanview found!! at $iview64_path !!"
    alias iview=run_iview
  fi
fi

# Rclone
# If you're using Ubuntu, it's pretty easy. Other than that, just
# install rclone and set it up for Google drive.
#
if [ -x "$(command -v rclone)" ]; then

	if [ ! -d $GOOGLE_DRIVE ]; then
		echo "Google drive mount point not found! making one.."
		mkdir -p $GOOGLE_DRIVE
	fi

	if mountpoint -q $GOOGLE_DRIVE; then
		echo "Google drive already mounted.."
	else
		echo "Mounting google drive to $GOOGLE_DRIVE"
		rclone mount google-drive: $GOOGLE_DRIVE &
		sleep 2
	fi
fi

# Geolocation
if [ -x "$(command -v jq)" ]; then
	echo "jq found, we can use geolocation alias as: geoloc"
	alias geoloc="curl -s https://ipvigilante.com/$(curl -s https://ipinfo.io/ip) | jq '.data.latitude, .data.longitude, .data.city_name, .data.country_name'"
fi

# starship
if [[ "$(echo $0)" == *bash ]]; then
  if [ -x "$(command -v starship)" ]; then
    echo "Starship found! Let's start it!"
	eval "$(starship init bash)"
  fi
fi

# zoxide
if [ -x "$(command -v zoxide)" ]; then
  echo "zoxide found! activating it!"
  if [[ "$(echo $0)" == *bash ]]; then
    eval "$(zoxide init bash)"
  elif [[ "$(echo $0)" == *zsh ]]; then
    eval "$(zoxide init zsh)"
  else
    eval "$(zoxide init posix --hook prompt)"
  fi
  alias cd='z'
fi
