#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
# startxfce4 &
# startlxde &

export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
export XDG_MENU_PREFIX="gnome-flashback-"

# Gnome session
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
#[ -x /etc/X11/Xsession ] && exec /etc/X11/Xsession
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
#xsetroot -solid grey
vncconfig -iconic &

dbus-launch --exit-with-session gnome-session &
