;;; packages.el -*- lexical-binding: t; -*-
(package! all-the-icons-dired)
(package! flycheck-aspell)
(package! async)
(package! dired-open)
;; (package! dmenu)
;; (package! elfeed)
;; (package! elpher)
;; (package! emms)
(package! emojify)
(package! evil-tutor)
(package! ivy-posframe)
(package! mastodon)
(package! peep-dired)
(package! pianobar)
(package! rainbow-mode)
(package! resize-window)
(package! tldr)
(package! wc-mode)
(package! writeroom-mode)
(package! rotate) ; Window pin
(package! info-colors) ; Pretty manual
(package! systemd) ; Editing systemd unit files
(package! graphviz-dot-mode) ; graphviz
(package! elvish-mode)
(package! ob-elvish)
(package! ob-cfengine3)
(package! iedit)
(package! annotate)
(package! org-auto-tangle)
