version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 9099:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - nextcloud:/var/www/html
    deploy:
      resources:
        limits:
          cpus: 2.50
          memory: 3072M
        reservations:
          cpus: 0.25
          memory: 256M

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: 1.25
          memory: 1024M
        reservations:
          cpus: 0.25
          memory: 256M


volumes:
  mysql:
  nextcloud:
